{{- if not .Values.database.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "golden-retriever-blog.fullname" . }}-secret
  labels:
    {{- include "golden-retriever-blog.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASS: {{ .Values.database.password | quote }}
{{- end }}
